
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA ID LBRACKET LPAREN MINUS NUMBER RBRACKET RPAREN STRINGstatement : expressionexpression : STRINGexpression : NUMBERexpression : IDexpression : ID LPAREN arglist RPARENarglist : expression COMMA arglistarglist : expression'
    
_lr_action_items = {'STRING':([0,6,10,],[3,3,3,]),'NUMBER':([0,6,10,],[4,4,4,]),'ID':([0,6,10,],[5,5,5,]),'$end':([1,2,3,4,5,9,],[0,-1,-2,-3,-4,-5,]),'COMMA':([3,4,5,8,9,],[-2,-3,-4,10,-5,]),'RPAREN':([3,4,5,7,8,9,11,],[-2,-3,-4,9,-7,-5,-6,]),'LPAREN':([5,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,6,10,],[2,8,8,]),'arglist':([6,10,],[7,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','imp_parse.py',145),
  ('expression -> STRING','expression',1,'p_expression_string','imp_parse.py',149),
  ('expression -> NUMBER','expression',1,'p_expression_number','imp_parse.py',153),
  ('expression -> ID','expression',1,'p_expression_id','imp_parse.py',157),
  ('expression -> ID LPAREN arglist RPAREN','expression',4,'p_expression_func','imp_parse.py',161),
  ('arglist -> expression COMMA arglist','arglist',3,'p_arglist_args','imp_parse.py',165),
  ('arglist -> expression','arglist',1,'p_arglist_expr','imp_parse.py',170),
]
